service:
  title: HawkerFlow Service Order
  root_path: '/order'
  port: 8080
  host: '0.0.0.0'
  allow_origins:
    - '*'
  methods:
    - '*'
  headers:
    - '*'
  docs_url: '/docs'
  redoc_url: '/redoc'
  reload: true
  scheme: 'http'
  credentials: true

datasource:
  driver:
    package: "drivers.postgres_driver"
    driver_class: "PostgresDriver"
  database:
    connection_url: 'sqlite:///database.db'
    driver_name: 'postgresql+psycopg2'
  options:
    echo: false

sqs:
  enabled: true
  queue_url: "http://localhost:4566/000000000000/order_queue"
  region_name: "ap-southeast-1"
  endpoint_url: "http://localhost:4566"
  wait_time_seconds: 5
  max_number_of_messages: 10
  visibility_timeout: 60

events:
  enabled: true
  topic_arn: "arn:aws:sns:us-east-1:000000000000:order_status"
  region_name: "ap-southeast-1"
  endpoint_url: "http://localhost:4566"